### ISSUE TITLE
sqlite3

### ISSUE THREAD

**Issue by Mikmonken** [ernitron/temperature-server#1]
Sorry never used Github before but though it might be useful to add this

---

/usr/bin/pip run on Thu May 19 13:30:59 2016
Requirement already satisfied (use --upgrade to upgrade): cherrypy in /usr/local/lib/python2.7/dist-packages/CherryPy-5.4.0-py2.7.egg (from -r requirements.txt (line 1))
Downloading/unpacking sqlite3 (from -r requirements.txt (line 2))
  Getting page https://pypi.python.org/simple/sqlite3/
  Could not fetch URL https://pypi.python.org/simple/sqlite3/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/sqlite3/ when looking for download links for sqlite3 (from -r requirements.txt (line 2))
  Getting page https://pypi.python.org/simple/
  URLs to search for versions for sqlite3 (from -r requirements.txt (line 2)):
- https://pypi.python.org/simple/sqlite3/
  Getting page https://pypi.python.org/simple/sqlite3/
  Could not fetch URL https://pypi.python.org/simple/sqlite3/: 404 Client Error: Not Found
  Will skip URL https://pypi.python.org/simple/sqlite3/ when looking for download links for sqlite3 (from -r requirements.txt (line 2))
  Could not find any downloads that satisfy the requirement sqlite3 (from -r requirements.txt (line 2))
  Cleaning up...
  No distributions at all found for sqlite3 (from -r requirements.txt (line 2))
  Exception information:
  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 290, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1178, in prepare_files
    url = finder.find_requirement(req_to_install, upgrade=self.upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 277, in find_requirement
    raise DistributionNotFound('No distributions at all found for %s' % req)
  DistributionNotFound: No distributions at all found for sqlite3 (from -r requirements.txt (line 2))

**Comment by ernitron** [comment]
I replied to your other comment.

Anyway I will comment out the sqlite3 requirement.

Thanks
